### PR TITLE
Popular subbed/dubbed support

### LINKED ISSUE #76: Add new section
I was hoping you could add a new section called "Most Watched" the link is here https://9anime.to/most-watched.

Makes it easier to find the popular animes.

### PR DESCRIPTION
**Pull request by Cozmmando**
Attempt at completing #76, but I can't get it to work. I would appreciate any kind of help.

The links I am using are https://9anime.to/filter?sort=views%3Adesc&language=dubbed and https://9anime.to/filter?sort=views%3Adesc&language=subbed. I believe the problem is in either default.py or NineAnimeBrowser.py shown below.

```
@route('popular_subbed')
def POPSUBBED(payload):
    return control.draw_items(_BROWSER.get_popular_subbed())

@route('popular_subbed/*')
def POPSUBBED_PAGES(payload):
    return control.draw_items(_BROWSER.get_popular_subbed(int(payload)))

@route('popular_dubbed')
def POPDUBBED(payload):
    return control.draw_items(_BROWSER.get_popular_dubbed())

@route('popular_dubbed/*')
def POPDUBBED_PAGES(payload):
    return control.draw_items(_BROWSER.get_popular_dubbed(int(payload)))
```

```
    def get_popular_dubbed(self,  page=1):
        return self._get_by_filter('popular_dubbed', {
            "language" : "dubbed",
            "sort" : "views:desc"
        }, page);

    def get_popular_subbed(self,  page=1):
        return self._get_by_filter('popular_subbed', {
            "language" : "subbed",
            "sort" : "views:desc"
        }, page);
```

I also attempted a translation. Bilinguals, feel free to fix it.

```
	<string id="30004">מתורגם פופולרי</string>
	<string id="30005">פופולרי</string>
```

I'm very new to this, so sorry if I made an obvious or stupid mistake. It's a learning experience.

Closes #76

### CODE REVIEW

**Comment by DxCx** [comment]
@Cozmmando thanks alot for the contribuation, you did it perfectly fine.
you just had to restart kodi couple of times till it decideds to get rid of his cache and really rerender it.

**Comment by DxCx** [comment]
btw, this is not good practice to work from master,
you should checkout for a new branch and open a PR from there.
i would suggest you to reset --hard your master to origin/master 👍

**Comment by Cozmmando** [comment]
@DxCx Sorry about that, I'm new to GitHub. How do I start a new branch?

**Comment by DxCx** [comment]
Nothing to be sorry :) the work you did was absolutlely fine. It is already merged and released.
That was a tip for next time for you :)

**Pull request merged**
