### PR TITLE
Fixes issue #221

### PR DESCRIPTION
**Pull request by SwagOtaku**
9anime changed image source url, this update to NineAnimeBrowser.py fixes image url extraction, which is the cause of issue #221.

### CODE REVIEW

**Comment by ForTheLoveOfTech** [comment]
Thanks for the fix SwagOtaku! Everything is back in order.

**Comment by pjcanales** [comment]
How do I use the fix?

**Comment by Sion87** [comment]
Worked like a charm!  Thanks @SwagOtaku

**Comment by dokoab** [comment]
@norhaji you can also replace the file directly in your Kodi installation. First you find your Kodi addons folder...

**Android:** /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/ (the .kodi folder is hidden, use ES File Explorer with the "Show hidden files" option)
**Windows:** AppData/Roaming/Kodi/addons/
**Linux:** /home/USER/.kodi/addons/

...and copy the [NineAnimeBrowser.py](https://github.com/SwagOtaku/plugin.video.9anime/raw/171fe295c0efd84db4f700d88c7f9f3320938b7d/resources/lib/NineAnimeBrowser.py) file over the same-name one, it's inside **plugin.video.9anime/resources/lib/**

(The way you did it probably involved less clicking...)

**Comment by DxCx** [comment]
Thanks for the fix @SwagOtaku !

**Pull request merged**
