### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tinymovingparts**
first pull request, I think I did it correctly?

### CODE REVIEW

**Comment by DxCx** [comment]
Uep you did it just great :)
Can you just also add your name under contributers?

**Comment by tinymovingparts** [comment]
@DxCx all done. Feel like I havn't really earned my spot up there just yet though. I noticed you didn't add a (most popular) section to the menu options. I was going to mess with my fork and try and added it in. mind checking my working and helping me out when i put in a pull request?

**Comment by DxCx** [comment]
Yeah ofcourse :) and thanks again

**Comment by tinymovingparts** [comment]
@dxcx making commits to my fork wouldn't effect your master branch without you accepting to merge a pull request correct? I don't want to risk messing up any of your work.

**Comment by DxCx** [comment]
yep, thats exactly how PR works like, you only suggest for changes but i need to accept them.

**Comment by tinymovingparts** [comment]
ok good to hear. have you tested the addon today? I tryed to make some changes and I was able to get most watched dubbed to work but not subbed. so i deleted all my changes. also on the your most recent version the options are hit or miss. sometimes they open sometimes they come up with an error.

**Comment by tinymovingparts** [comment]
downgraded to 0.0.9 and the options work fine it might just be my internet timing out. Like I mentioned it the new options work sometimes.

**Comment by DxCx** [comment]
Hmm, for some reason kodi doesnt invalidate cache properly. Not sure how other plugins are adding changes like that but thats the reason it acts wired..
When i restarted kodi it just fixed itself

**Comment by tinymovingparts** [comment]
ok got it so a temporary fix would just be to restart kodi when it gives an error, but a long term fix would be to find someway to rest the cache each time so that cache is valid each time it retrieves the list of shows from the site?

**Comment by DxCx** [comment]
wait.. what?
hmm, what i meant is that when adding more sections to main view the first time is cached usually so we need to forcefully refersh it.
once it's refresehd it just works...

**Comment by tinymovingparts** [comment]
ohhh ok got it, thanks for the reply.

**Pull request merged**
