### PR TITLE
fix: NineAnimeExtender Token (By ThePyrotechnic)

### PR DESCRIPTION
**Pull request by DxCx**
Closes #256

### CODE REVIEW

**Comment by nateclub** [comment]
@DxCx so since it’s fixed all I need to do is update it? Or am I gonna have to get the upgrade token from the pc and import it to my firestick?

**Comment by Blackreaper17** [comment]
Update is up for firestick users

**Comment by DxCx** [comment]
Yes @nateclub using version 0.0.38 should fix the token :)

**Comment by Osoreru9281** [comment]
I check for updates but only see Version 0.0.37

**Pull request merged**
