### PR TITLE
Duplicated Episode Fix

### PR DESCRIPTION
**Pull request by HackedGameMaker**
I'm testing to see if I can fix the duplicated links glitch. If I'm successfully hopefully the creator will ad to the original build.

### CODE REVIEW

**Comment by DxCx** [comment]
im not sure which duplicate thing you mean..
can you eleborate please? does it have an open ticket?

**Comment by HackedGameMaker** [comment]
Sorry I forgot to mention what the duplicated thing was, it's because you know how there are two episode one's well I'm trying to figure out how to bypass that. For example I'm using the show My First Girlfriend is a Gal which has two episode one's, one being censored and the other being uncensored and since they're both episode one's on the plugin on the website they're listed differently. Since I haven't coded for some time I have messed up a little but I am slowly making some progress so hopefully I can get the issue fixed soon. If you have any advice I would really appreciate it.

**Comment by epicshot01** [comment]
Good luck, I hope it’ll work out

**Comment by FireWolf74** [comment]
Wait a Second dude many of the Duplicated Episodes could be the Censored and Uncensored and Sub or Dub.

**Comment by HackedGameMaker** [comment]
Well I was going to open up a new pull request to show the creator what I've discovered about the naming of each episode and hopefully he or someone else can figure out how to edit it so that we can finally fix the issue.

**Comment by ghettowboy** [comment]
I wish I was a coder sometimes, but can't you use a IF/ELSE statement for this? It seems like that is the way the add-on pulls and parses the episode info. Using an if/else you should be able to finish your naming thought. Like IF ("Uncen" isin %s blah, blah, blah) Else (return normal result). I don't know, maybe, if you considered that?

**Pull request closed without merging**
