### PR TITLE
Update Login Feature

### PR DESCRIPTION
**Pull request by SwagOtaku**
- Updates updating anime status
- Adds tld support for login
- Adds 9anime episode tracking ( i.e. updates the episode number displayed when accessing watchlist on 9anime site)

### CODE REVIEW

**Comment by SwagOtaku** [comment]
The general tab in settings was getting a bit clunked up so moved the 9anime login stuff into a new tab. Also tweaked the episode tracking so you can enable/disable it from settings.

**Comment by SwagOtaku** [comment]
Updated domain, which fixes issue #315

**Comment by SwagOtaku** [comment]
@DxCx made the requested changes.
Thanks

**Comment by DxCx** [comment]
can you please rebase to fix the conflict?

**Comment by SwagOtaku** [comment]
@DxCx never used git bash before, im having trouble trying to rebase :(

**Pull request closed without merging**
